.. -*- coding: utf-8 -*-

=========================================
Computergestützte Mathematik zur Analysis
=========================================

-------------------------------------------------------------------
Übersicht über die verwendeten Befehle, nach Lektionen geordnet
-------------------------------------------------------------------

.. contents:: Inhaltsverzeichnis
              :backlinks: none

Lektion 1
*********

Arithmetik
==========

+     Befehle werden mit ``;``
      oder ``:`` abgeschlossen.  Im
      ersten Fall wird das Ergebnis angezeigt, im zweiten nicht.  
      Zeilenende impliziert ``;``

+     ``+, -, *, /, ^``

      arithmetische Operatoren

+     ``!``

      Faktorielle

+     ``evalf(`` *x* ``)``

      numerische Auswertung von *x* auf 10 gültige Stellen

+     ``evalf(`` *x* ``,`` *n* ``)``

      numerische Auswertung von *x* auf *n* gültige Stellen      

+     ``Digits`` := *n*

      setzt die Genauigkeit auf *n* Stellen

Variablen
=========

+     ``:=``

      Zuweisung

+     ``=``

      Vergleichsoperator (später)

+     *a* ``:= '`` *a* ``'``

      Aufhebung einer Zuweisung

elementare Funktionen
=====================

+     ``sqrt``

      Quadratwurzel

+     ``sin, cos, tan, cot``

      trigonometrische Funktionen

+     ``arcsin, arccos, arctan, arccot``

      inverse trigonometrische Funktionen

..      ``arctan`` siehe auch in `Der Arcustangens`_

+     ``log, ln``

      natürlicher Logarithmus

+     ``exp``

      Exponentialfunktion

+     ``Pi``

      Ludolfsche Zahl pi
  
Vereinfachungen
===============

+     ``simplify``

      allgemeiner Vereinfachungsbefehl, siehe auch in Ersetzungen_

+     ``normal``

      Kürzen von Brüchen

+     ``normal(`` *f* ``, expanded)``
 
      dasselbe, aber Zähler und Nenner werden expandiert

+     ``expand``

      expandiert Polynome, trigonometrische Funktionen usw.

+     ``factor``

      faktorisiert Polynome

Hilfsprogramme
==============

+     ``restart``

      löscht alle Variablen

+     ``lprint``

      Ausgabe in 1D 

zurück zum Inhaltsverzeichnis_



Lektion 2
*********

dito Operator
=============

+     %

      Ergebnis der letzten Berechnung

+     Zugriff auf label ist nur mit der Maus möglich


Summen und Grenzwerte
=====================

+     ``sum(`` *f*, *n* ``=`` *a* ``..`` *b* ``)``

      Summe von *f* für *n* von *a* bis *b*, dabei ist *f* ein Ausdruck in *n*

+     ``infinity``

      Konstante unendlich

+     ``limit(`` *f* ``,`` *x* ``=`` *a* ``)``

      Grenzwert des Ausdrucks *f* in *x* = *a*

+     ``limit(`` *f* ``,`` *x* ``=`` *a* ``, right)``

      Grenzwert des Ausdrucks *f* in *x* = *a* von rechts (von links
      mit ``left``)

Ableitungen und Integrale
=========================

+     ``diff(`` *f* ``,`` *x* ``)``

      Ableitung des Ausdrucks *f* nach *x*

+     ``int(`` *f*, *x* ``)``

      Stammfunktion des Ausdrucks *f* bezüglich der Variablen *x*

+     ``int(`` *f*, *x* ``=`` *a* ``..`` *b* ``)``

      bestimmtes Integral

+     ``Int``

      Integral nur anzeigen

Ersetzungen
===========

+     ``eval(`` *expr* ``, {`` *a* ``=`` *A* ``,`` *b* ``=`` *B* ``,``
      ... ``,`` *z* ``=`` *Z* ``})``

      in *expr* werden *a*, *b*, ..., *z* durch  *A*, *B*, ..., *Z* ersetzt.

+     ``simplify(`` *epr* ``, {`` *a* ``=`` *A* ``,`` *b* ``=`` *B* ``,``
      ... ``,`` *z* ``=`` *Z* ``})``

      Vereinfachung unter den angegebenen Nebenbedingungen

+     ``collect(`` *p* ``,`` *x* ``)``

      fasst im Polynom *p* alle *x*-Potenzen zusammen (*p* muss
      expandiert sein) 

Ausdrücke vs Funktionen
=======================

+     ``(`` *a* ``,`` *b* ``,`` ... ``,`` *z* ``) ->`` *expr*

      Funktion der Variablen *a*, *b*, ..., *z*, deren Funktionsvorschrift
      durch *expr* gegeben ist 
 
+     ``unapply(`` *expr* ``,`` *a* ``,`` *b* ``,`` ... ``,`` *z* ``)``

      wandelt den Ausdruck *expr* in eine Funktion der Variablen *a*, *b*,
      ..., *z* um	

Funktionsgraphen
================

+     ``plot(`` *expr* ``,`` *x* ``=`` *a* ``..`` *b* ``)``

      zeigt den Graph des Ausdrucks *expr* für *x* von *a* bis *b*

+     ``plot(`` *f* ``,`` *a* ``..`` *b* ``)``

      zeigt den Graph der Funktion *f* über dem Intervall [*a*, *b*]

+     ``plot([`` *ex_1* ``,`` *ex_2* ``,`` ... ``,`` *ex_n* ``],`` *x*
      ``=`` *a* ``..`` *b* ``, color = [`` *farbe_1* ``,`` *farbe_2* 
      ``,`` ... ``,`` *farbe_n*	``])``

      zeigt die Graphen der Ausdrücke *ex_1*, *ex_2*, ..., *ex_n* für
      *x* von *a* bis *b* in einem Fenster, jeden in der angegebenen
      Farbe 

+     ``plot([`` *f_1* ``,`` *f_2* ``,`` ... ``,`` *f_n* ``],`` *a* ``..`` 
      *b* ``, color = [`` *farbe_1* ``,`` *farbe_2* ``,`` ... ``,`` 
      *farbe_n* ``])``

      dasselbe für Funktionen 

+     hinter dem Argumentbereich kann ein Wertebereich in der
      gleichen Form angegeben werden 

+     Die folgenden Optionen können nachgestellt werden
      
      +  ``axes = boxed``

         Koordinatenachsen; Alternativen sind ``normal``, ``framed``, ``none``

      +  ``discont = true``

	 Suche nach Sprungstellen einschalten

      +  ``thickness =`` *n*

	 Strichdicke, erlaubt sind *n* = 0,1,2,3

      +  ``numpoints =`` *n*

	 *n* Funktionsauswertungen verwenden

      +  ``scaling = constrained``

	 alle Achsen verwenden denselben Maßstab

..      siehe auch `ebene parametrische Plots`_ und `logplot` im
..      Abschnitt Datenimport_


Maple rechnet komplex
=====================

+     ``I``

      imaginäre Einheit

+     ``sqrt(`` *x* ``)``

      Quadratwurzel

+     ``Re(`` *z* ``), Im(`` *z* ``)``

      Real- und Imaginärteil

+     ``conjugate(`` *z* ``)``

      komplex Konjugierte 

+     ``abs(`` *z* ``)``

      Absolutbetrag

*     ``csgn``

      komplexe Vorzeichenfunktion

+     *befehl* ``assuming`` *property_1* ``,`` *property_2* ``,`` ... ``,``
      *property_n*

      *befehl* wird unter den zusätzlichen Annahmen *property_1*, ...,
      *property_n* ausgeführt

      wichtige Beispiele für properties:
      
      *		*x* ``> 2``

      *         *y* ``<=`` *x*

      *         *x* ``::real``

      *		*x* ``::positive``

      *		*n* ``::integer``

      *		*n* ``::odd``

      *		*n* ``::even``

+     ``evalc(`` *ausdruck* ``)``

      ausdruck wird unter der Annahme ausgewertet, dass alle
      auftretenden Variablen reell sind      

Lektion 3
*********

3D-Funktionsgraphen
===================

+     ``plot3d(`` *expr* ``,`` *x* ``=`` *a* ``..`` *b* ``,`` 
      *y* ``=`` *c* ``..`` *d* ``)``

      zeigt den Graph des Ausdrucks *expr* für *x* von *a* bis *b* und
      *y* von *c* bis *d*

+     ``plot3d(`` *f* ``,`` *a* ``..`` *b* ``,`` *c* ``..`` *d* ``)``

      zeigt den Graph der Funktion *f* über dem Rechteck [*a*,
      *b*]x[*c*, *d*]

+     Zusätzliche Optionen nur für 3D

      * ``view =`` *e* ``..`` *f*

	Wertebereich auf [*e*, *f*] einschränken

      * ``shading = zhue``

	höhenabhängige Farbwerte

      * ``style = patchcontour``

	Höhenlinien, Alternativen: ``patch``, ``patchnogrid``, ``wireframe``

      * ``transparency =`` *t*

	Transparenz festlegen, *t* liegt zwischen 0 und 1, dabei führt
	1 zu einem vollständig durchsichtigen Plot

      * ``orientation = [`` *phi* ``,`` *psi* ``]``

	Ort des Betrachters festlegen


Listen und Mengen
=================

+     ``[`` *a* ``,`` *b* ``,`` ... ``,`` *z* ``]``

      Liste

+     ``{`` *a* ``,`` *b* ``,`` ... ``,`` *z* ``}``

      Menge

+     *a* ``,`` *b* ``,`` ... ``,`` *z*

      Folge (Achtung: eine Folge wird nicht als Einzelobjekt
      verstanden) 

+     ``seq(`` *ausdr* ``,`` *j* ``=`` *a* ``..`` *b* ``)``

      Erzeugung einer Folge

+     ``nops(`` *liste* ``)``
   
      Anzahl der Elemente; statt *liste* ist auch eine Menge oder
      eine Folge zulässig

+     ``convert(`` *expr*, *type* ``)``

      Umwandlung des Ausdrucks *expr* in ein Objekt des Typs *type*.
      Wichtige Typen sind:

      * list

      Liste

      * set

      Menge

      * ``'+'``

      Summe

      siehe auch `Trigonometrische Funktionen`_

Schleifen
=========

+     ``for`` *l* ``in`` *list* ``do;`` *befehl_1* ``;``
      ... *befehl_n* ``; end do;``

      Schleife über alle Elemente der Liste *list*

+     ``for`` *i* ``from`` *a* ``to`` *b* ``do;`` 
      *befehl_1* ``;`` ... *befehl_n* ``; end do;``

      Schleife für *i* von *a* bis *b*, beide einschließlich 

Lektion 4
*********

automatisches Lösen von Gleichungen
===================================

+     ``solve(`` *Glg* ``,`` *x* ``)``

      löst Gleichung *Glg* nach der Variablen *x*

+     ``solve(`` *Gls* ``,`` *vars* ``)``

      löst Gleichungssystem *Gls* nach den Variablen
      *vars*, dabei sind *Gls* und *vars* Mengen

+     ``solve(`` ..., ``Explicit)``

      ``RootOf``-Notation wird nach Möglichkeit vermieden

+     ``is(`` *expr* ``)``

      stellt den Wahrheitsgehalt von *expr* fest

+     ``fsolve``

      wie ``solve``, aber numerisch;

      folgende Optionen
      
      *		``complex``

		suche auch nach komplexen Nullstellen

      *		*x* ``=`` *x_0*

		Startwert der Suche ist x_0

+     ``RootOf``

      Notation zur Darstellung von Lösungen

+     ``map(`` *f* ``,`` *liste* ``,`` *opt* ``)``

      auf alle Elemente von *liste* wird die Funktion *f* angewandt; 
      *opt* ist eine Folge von Optionen der Funktion *f*,
      die auch leer sein darf 

Pakete
======

+     ``with(`` *paket* ``)``

      lädt die Bibliothek *paket*
  
Graphen von Lösungsmengen
=========================

+     ``with(plots)``

      lädt das Paket mit speziellen Grafikfunktionen

+     ``implicitplot(`` *Glg* ``,`` *x* ``=`` *a* ``..`` *b* ``,``
      *y* ``=`` *c* ``..`` *d* ``)`` 

      zeichnet die Lösungsmenge der Gleichung *Glg* in den
      Variablen *x* und *y* im angegebenen Bereich; statt
      einer Gleichung ist auch eine Menge von Gleichungen
      zulässig; es dürfen Plotoptionen angeschlossen werden;
      ``implicitplot`` gehört zum Paket ``plots``

+     ``plot_real_curve(`` *p* ``,`` *x* ``,`` *y* ``)``

      zeichnet die Nullstellen des Polynoms *p* in den Variablen *x*
      und *y*; Plotoptionen sind zulässig; ``plot_real_curve`` gehört
      zum Paket ``algcurves``

Lösen von Polynomgleichungen
============================

+ ``@``

  Verknüpfungsoperator

Lösung transzendenter Gleichungen
===================================

+ ``solve(`` ..., ``allsolutions)``

  bei transzendenten Gleichungen alle Lösungen bestimmen 

+ ``about(`` *x* ``)``

  bestehende Annahmen über *x* anzeigen

+ ``fsolve(`` *Glg* ``,`` *x* ``=`` *a* ``..`` *b* ``)``

  Option von ``fsolve``, um den Suchbereich einzuschränken

+ ``series(`` *expr*, ``,`` *x* ``=`` *a* ``,`` *n* ``)``

  Reihenentwicklung des Ausdrucks *expr* im Punkt *a* nach der
  Variablen *x* zur Ordnung *n*.  Der Punkt darf *infinity* sein.

Lektion 05
**********

Träge Operatoren
================

+ ``Sum, Int, Diff``

  Varianten vom ``sum``, ``int``, ``diff``, bei denen Summe, Integral
  und Ableitung nur dargestellt, aber nicht ausgewertet werden

+ ``value``
  
  Befehl zur Auswertung der trägen Operatoren

Zusammenfassen
===============

+ ``collect(`` *poly* ``,`` *var* ``)``

  *poly* ist ein expandiertes Polynom; die Terme gleicher Potenz in
  *var* werden zusammengefasst
 
+ ``collect(`` *poly* ``,`` *liste* ``)``

  dasselbe für Polynome in mehreren Veränderlichen; die zu
  berücksichtigenden Veränderlichen sind in *liste* aufgezählt und
  werden der Reihe nach abgearbeitet

Trigonometrische Funktionen
===========================

+ ``sin``, ``cos``, ``tan``, ``cot``, ``arcsin``, ``arccos``,
  ``arctan``

  Trigonometrische Funktionen

+ ``expand``

  Anwendung der Additionstheoreme auf trigonometrische Funktionen

+ ``combine``

  Umkehrung von ``expand``, wo sinnvoll

+ ``trigsubs``

  schlägt äquivalente trigonometrische Ausdrücke vor

+ ``convert(`` *ausdruck* ``, sincos)``

  Tangens und exp(*ix*) werden in Sinus- und Cosinusfunktionen
  umgewandelt

Potenzfunktionen
================

+ ``surd(`` *x* ``,`` *n* ``)``

  reelle *n*-te Wurzel aus reellem *x*

Integration
===========

+ ``piecewise``

  stückweise definierter Ausdruck

gesteuerte Integration
======================

+ ``Change(`` *Int* ``,`` *ersetzung* ``)``

  Integration durch Substitution, hierbei sind *ersetzung* die
  Substitution als Gleichung und *Int* ein unausgewertetes Integral;
  ``Change`` ist Bestandteil des Pakets ``IntegrationTools``

+ ``Parts(`` *Int* ``,`` *u* ``)``

  Partielle Integration, hierbei ist *Int* ein unausgewertetes
  Integral und *u* der Faktor, der abgeleitet wird; ``Parts`` ist
  Bestandteil des Pakets ``IntegrationTools``

Lektion 06
**********

Grenzwerte
==========

+ ``Limit``

  träger Operator zu ``limit`` (s. `Summen und Grenzwerte`_)

Reihen
======

+ ``print``

  Ausgabe in normaler Qualität (im Gegensatz zu lprint (siehe
  Hilfsprogramme_))

+ ``#``

  Kommentar


Unendliche Produkte
===================

+     ``product(`` *f*, *n* ``=`` *a* ``..`` *b* ``)``

      Produkt über *f* für *n* von *a* bis *b*, dabei ist *f* ein
      Ausdruck in *n* 

+     ``Product``

      zugehöriger träger Operator

Taylorpolynom
=============

+	``convert(`` *reihe*, ``polynom)``

	Entfernen des Terms ``O(`` *x* ``^`` *n* ``)`` aus der Ausgabe
	von ``series``

Das komplex Bild
================

+       ``display({`` *pl1* ``,`` ... ``,`` *pln* ``})``
	
	zeigt die Plots *pl1* bis *pln* in einem Bild an.  ``display``
	gehört zum Paket ``plots``


Lektion 07
**********

Vektoren und Matrizen 
=====================

+ ``<`` *a*, *b*, ..., *z* ``>``

	Spaltenvektor

+ ``<`` *a* ``|`` *b* ``|`` ... ``|`` *z* ``>``

	Zeilenvektor

+ ``<`` *z1*, *z2*, ..., *zn* ``>``

	Matrix, aufgebaut aus Zeilenvektoren *z1*, *z2*, ...

+ ``<`` *s1* ``|`` *s2* ``|`` ... ``|`` *sn* ``>``

	Matrix, aufgebaut aus Spaltenvektoren *s1*, *s2*, ...

+ ``.``

	Matrixprodukt

+ ``Matrix``

	Erzeugung von Matrizen; Spezialfälle sind

	+ ``Matrix(`` *vector*, ``shape = diagonal)``

		erzeugt Diagonalmatrix aus einem Vektor

	+ ``Matrix(`` *n*, ``shape = identity)``

		erzeugt *n* x *n* Einheitsmatrix

+ ``Determinant``

	Determinante; der Befehl ``Determinant`` gehört zum Paket
	``LinearAlgebra``


Matrixplot
==========

+	``matrixplot(`` *M* ``, heights=histogram)``

	3D-Plot, dessen Höhen durch die Einträge der
	Matrix *M* gegeben werden; ``matrixplot`` gehört zum Paket
	``plots``

Lineare Gleichungssysteme
=========================

+	``GenerateMatrix(`` *ListevonGleichungen*, *Variablen*,
        *Option* ``)``
	  
	erzeugt Matrix zu dem durch *ListevonGleichungen* in den
	*Variablen* gegebenen Gleichungssystem; mögliche *Option* ist
	``augmented = true``, dies zeigt an, dass eine Spalte mit der
	rechten Seite angebaut werden soll; ``GenerateMatrix`` gehört zum Paket
	``LinearAlgebra``      

+	``LinearSolve(`` *A*, *b* ``)``

	löst die Matrixgleichung *Ax* = *b*; ``LinearSolve`` gehört zum Paket
	``LinearAlgebra``

+	``ReducedRowEchelonForm(`` *A* ``)``

	Zeilenstufenform von *A*; ``ReducedRowEchelonForm`` gehört zum Paket
	``LinearAlgebra``

Zeilenweise Manipulation
========================

+	``RowOperation``

	Sammelbefehl für die zeilenweise Manipulation von Matrizen;
	``RowOperation`` gehört zum Paket ``LinearAlgebra``	

+	``Rank``

	Rang einer Matrix; gehört zum Paket ``LinearAlgebra``


Normalformen
============

+	``Eigenvalues(`` *A* ``)``

	Eigenwerte von *A*; ``Eigenvalues`` gehört zum Paket
	``LinearAlgebra`` 

+	``Eigenvectors(`` *A* ``)``

	Eigenwerte und -vektoren von *A*; ``Eigenvectors`` gehört zum Paket
	``LinearAlgebra``

+	``JordanForm(`` *M* ``, output = ['J', 'Q'])``

	Jordansche Normalform von *M*, ausgegeben wird die Jordanform
	zusammen mit der zugehörigen Matrix der Hauptvektoren;
	``JordanForm`` gehört zum Paket ``LinearAlgebra``

+	``SubMatrix``

	Teilmatrix, ``SubMatrix`` gehört zum Paket ``LinearAlgebra``


Andere Operationen mit Matrizen
===============================

+       ``Transpose``

	Transponierte, ``Transpose`` gehört zum Paket ``LinearAlgebra``

+       ``DotProduct(`` *u* ``,`` *v* ``)``

	Skalarprodukt, wobei der erste Faktor komplex konjugiert wird; 
	die Option ``conjugate=false`` verhindert das.  ``DotProduct``
	gehört zum Paket ``LinearAlgebra``

Lektion 08
**********

ebene parametrische Plots 
=========================

+ ``plot([`` *x*, *y*, *t* ``=`` *a* ``..`` *b* ``],`` *Optionen* ``)``

	zeichnet die durch die Ausdrücke *x* und *y* gegebene ebene
	Kurve, dabei sind *x* und *y* Ausdrücke in *t*; statt einer
	einzelnen Kurve ist auch eine Menge von Kurven möglich

+ ``polarplot([`` *r*, *phi*, *t* ``=`` *a* ``..`` *b* ``],`` *Optionen* ``)``

	dasselbe, aber für Polarkoordinaten *r* und *phi*;
	``polarplot`` gehört zum Paket ``plots``

Der Arcustangens
================

+ ``arctan(`` *y*, *x* ``)``

	Winkel des Punktes *x* + i *y* gegen die positive reelle Achse

Polygonzüge
===========

+ ``plot (`` *liste* ``)``

        zeichnet das durch eine Liste von Datenpunkten gegebene Polygon

Datenimport
===========

+ ``read(`` *Dateiname* ``)``

	liest Maplekommandos aus Datei mit Namen *Dateiname*; der Name
	sollte in Anführungsstriche ``"`` eingeschlossen sein

+ ``logplot``

        halblogarithmischer Graph

+ ``save(`` *a* ``,`` ... ``,`` *z* ``,`` *Dateiname* ``)``

        schreibt die angegebenen Ausdrücke in die Datei


Raumkurven 
==========

+ ``spacecurve([`` *x*, *y*, *z*, *t* ``=`` *a* ``..`` *b* ``],`` *Optionen* ``)``

	zeichnet die durch die Ausdrücke *x*, *y* und *z* gegebene
	Raumkurve, dabei sind *x*, *y* und *z* Ausdrücke in *t*; statt
	einer einzelnen Kurve ist auch eine Menge von Kurven möglich;
	``spacecurve`` gehört zum Paket ``plots``

+ ``tubeplot([`` *x*, *y*, *z*, *t* ``=`` *a* ``..`` *b* ``], radius =`` *r* ``,`` *Optionen* ``)``

        wie spacecurve, aber statt einer Raumkurve wird ein Schlauch
	der angegebenen Dicke gezeigt

	zusätzliche Optionen sind hier

	+ ``color = [`` *r*, *g*, *b* ``]``

		    Angabe eine Färbefunktion als RGB-Wert; dabei sind
		    *r*, *g* und *b* Ausdrücke im Parameter *t*

        + ``color`` = *h*

		    Angabe einer Färbefunktion durch einen Parameter
		    *h*, der ein Ausdruck im Parameter *t* ist



Flächen im Raum 
===============

+ ``plot3d([`` *x*, *y*, *z* ``],`` *s* ``=`` *a* ``..`` *b*, *t* 
  ``=`` *c* ``..`` *d*, *optionen* ``)``

	zeichnet die durch die Ausdrücke *x*, *y* und *z* gegebene
	Fläche im Raum; dabei sind *x*, *y* und *z* Ausdrücke in den
	Parametern *s* und *t*

	zusätzliche Optionen sind hier

	+ ``color = [`` *r*, *g*, *b* ``]``

		    Angabe eine Färbefunktion als RGB-Wert; dabei sind
		    *r*, *g* und *b* Ausdrücke in den Parametern *s*
		    und *t*

        + ``color`` = *h*

		    Angabe einer Färbefunktion durch einen Parameter
		    *h*, der ein Ausdruck in den Parametern *s* und
		    *t* ist


Ableitungen von Vektorfunktionen
================================

+	``VectorCalculus``

	Paket zur Differentialrechnung mehrerer Veränderlicher

+	``BasisFormat(false)``

	Gradienten etc. werden in der gewohnten Tupelschreibweise
	ausgegeben.  ``BasisFormat`` gehört zum Paket
	``VectorCalculus``.

Gradienten und der Laplace-Operator
===================================

+	``Gradient(`` *f*, *liste* ``)``

	Gradient von *f* nach den in *liste* aufgezählten Variablen.
	``Gradient`` gehört zum Paket ``VectorCalculus``.
 
+       ``Laplacian(`` *f*, *liste* ``)``

	Laplace-Operator von *f* nach den in *liste* aufgezählten
	Variablen. ``Laplacian`` gehört zum Paket ``VectorCalculus``.

Lektion 9
*********

Norm eines Vektors
==================

+	``Norm``

	Norm eines Vektors oder einer Matrix; ``Norm`` gehört zum
	Paket ``LinearAlgebra``.  Nicht zu verwechslen mit der Norm
	eines Vektorfelds (s. Vektorfelder_)	

Das Kreuprodukt
===============

+	``CrossProduct``

	Kreuzprodukt; ``CrossProduct`` gehört zum Paket ``LinearAlgebra``

Vektorfelder
============

+	``VectorField(`` *vektor* ``, cartesian[`` *liste* ``])``

	*vektor* ist ein Vektor, der ein Ausdruck in den in *liste*
        aufgezählten Variablen ist.  ``VectorField`` gehört zum Paket
	``VectorCalculus``.

+	``fieldplot(`` *vf*, *x* = *a* ``..`` *b*, *y* = *c* ``..``
	*d*, *optionen* ``)``

	Darstellung des ebenen Vektorfelds *vf* durch Pfeile.  *vf*
	ist ein Vektorfeld in den Variablen *x* und *y*.  Die Anzahl
	der Pfeile kann mit ``grid`` beeinflusst
	werden.  ``fieldplot`` gehört zum Paket ``plots``.

	zusätzliche Optionen sind hier

	+ ``fieldstrength = log``

	          Pfeillänge hängt logarithmisch von der Norm des
		  Vektorfelds ab; andere Möglichkeit ist ``fixed``

+	``fieldplot3d(`` *vf*, *x* = *a* ``..`` *b*, *y* = *c* ``..``
	*d*, *z* = *e* ``..`` *f*, *optionen* ``)``

	Darstellung des 3D-Vektorfelds *vf* durch Pfeile.  *vf*
	ist ein Vektorfeld in den Variablen *x*, *y* und *z*.  Die Anzahl
	der Pfeile kann mit ``grid`` beeinflusst
	werden.  ``fieldplot3d`` gehört zum Paket ``plots``.

+       ``Norm``

	Die Norm eines Vektorfelds.  Gehört zum Paket
	``VectorCalculus``. Gibt Funktion zurück.  Nicht zu
	verwechseln mit der Norm eines Vektors aus dem Paket
	``LinearAlgebra`` (s. `Norm eines Vektors`_)

Taylorpolynom in mehreren Veränderlichen
========================================

+	``mtaylor(`` *A* ``,`` *liste* ``,`` *n* ``)``

	Taylorentwicklung des Ausdrucks *A* nach den Variablen in
	*liste* bis zur totalen Ordnung *n* ausschließlich


----------------------

© 2014 `Rüdiger Braun`_

zurück zur Homepage_ 

.. _Homepage: http://compana.ruediger-braun.net
.. _`Rüdiger Braun`: mailto:Ruediger.Braun@uni-duesseldorf.de
